### ISSUE TITLE
Unable to connect from proxy URL to actual upstream URL

### ISSUE THREAD

**Issue by amit1990sumit** [Shopify/toxiproxy#217]
Hi Team,
Install toxiproxy using below command in mac
"brew tap shopify/shopify"
"brew install toxiproxy" 

Running the "./toxiproxy-server", then run the "toxiproxy-cli" and create below proxy name. 
`Name: shopify_test_redis_master	Listen: 127.0.0.1:26379	Upstream: http://devimages.apple.com
`
But when I am hitting the  "127.0.0.1:26379", it does not redirect to "http://devimages.apple.com".
It gives error 
```
INFO[11596] Accepted client                               client=127.0.0.1:61558 name=shopify_test_redis_master proxy=127.0.0.1:26379 upstream=http://devimages.apple.com
ERRO[11596] Unable to open connection to upstream         client=127.0.0.1:61558 name=shopify_test_redis_master proxy=127.0.0.1:26379 upstream=http://devimages.apple.com
```
Also, Is it possible that from proxy URL I can throttled different path of actual URL. For example

Listen : 127.0.0.1:26379
Upstream: http://devimages.apple.com
Actual URL : http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
Proxy URL : 127.0.0.1:26379/iphone/samples/bipbop/bipbopall.m3u8

Please help.

**Comment by philsturgeon** [comment]
I'm experiencing exactly this error trying to use it in docker-compose, talking to `id` (another docker-compose container made available over the `foo_dev` network. 

```
time="2018-06-27T21:25:11Z" level="info" msg="Accepted client" name="id_dev_http" client=172.18.0.5:36000 proxy="[::]:26080" upstream="id"
time="2018-06-27T21:25:11Z" level="error" msg="Unable to open connection to upstream" client=172.18.0.5:36000 proxy="[::]:26080" upstream="id" name="id_dev_http"
time="2018-06-27T21:25:11Z" level="info" msg="Accepted client" name="id_dev_http" client=172.18.0.5:36002 proxy="[::]:26080" upstream="id"
time="2018-06-27T21:25:11Z" level="error" msg="Unable to open connection to upstream" proxy="[::]:26080" upstream="id" name="id_dev_http" client=172.18.0.5:36002
```

I can`curl -X GET http://id` from inside the toxiproxy service.

```
services:
  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    expose:
      - "8474"
      - "26080"
    volumes:
      - ${PWD}:/app
    command: -config /app/config/proxies.json -host 0.0.0.0
    networks:
      - default
      - foo_dev

  base:
    environment:
      - ID_URI=http://toxiproxy:26080/
    depends_on:
      - redis
      - toxiproxy
```

This is a `docker-compose.toxiproxy.yml` file that extends our normal `docker-compose.yml`. As far as docker networking seems to be concerned everything is fine, but toxiproxy cannot connect to the upstream for some reason, and several of us have scratched our heads for a long time over why. 

Not very sure what `client=172.18.0.5:36002` is meant to be. 

```
PING id (172.19.0.11): 56 data bytes
64 bytes from 172.19.0.11: seq=0 ttl=64 time=0.120 ms

PING toxiproxy (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: seq=0 ttl=64 time=0.055 ms
```

```
cat config/proxies.json
[
  {
    "name": "id_dev_http",
    "listen": "0.0.0.0:26080",
    "upstream": "id"
  }
]
