### ISSUE TITLE
running toxiproxy inside a container and access to upstream service from host machine

### ISSUE THREAD

**Issue by muatik** [Shopify/toxiproxy#252]
I cannot access to the upstream service when I run toxiproxy inside a docker container. 

I have the following proxy configuration.
```json
{
    "product-service": {
        "name": "product-service",
        "listen": "[::]:8379",
        "upstream": "product-service:8014",
        "enabled": true,
        "toxics": []
    }
}
```

toxiproxy and upstream service run in separate docker containers. inside toxiproxy container, I can access to upstream service, `curl localhost:8379` but on my host machine, I can't. here is my docker-compose config:

```yml
  product-service:
    image: my-image
    ports:
      - "8014: 8014"
  toxiproxy:
    image: shopify/toxiproxy
    links:
      - product-service
    ports:
      - "8474:8474"
      - "8379:8014"
```

what could be the reason?
