### ISSUE TITLE
Import toxics from config.json

### ISSUE THREAD

**Issue by marcelothebuilder** [Shopify/toxiproxy#281]
Example, when importing this through docker:
```
[
  {
    "name": "es1",
    "listen": "[::]:9200",
    "upstream": "elasticsearch:9200",
    "enabled": true,
    "toxics": [
      {
        "name": "toxictest",
        "type": "latency",
        "stream": "upstream",
        "toxicity": 1.0,
        "attributes": {
          "latency": 15000,
          "jitter": 15000
        }
      }
    ]
  },
```

Using docker-compose.yml like this:
```
 toxiproxy:
    image: shopify/toxiproxy
    hostname: toxiproxy
    networks:
      - removed
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5432:5432"
      - "8474:8474"
    command: -host=0.0.0.0 -config=/etc/config.json
    volumes:
      - ./toxiproxy/config.json:/etc/config.json
```

The specified toxic `toxictest` won't be imported. I think this is by design, but is there a nice way around this?
